### ISSUE TITLE
Team3 Review: Non-Functional Requirement for Language

### ISSUE THREAD

**Issue by arkinmodi** [NevoAbigail/Capstone#11]
> NFR1: Can be used by people of any language.
> Verification: App will be verified by test users who do not know english.

This is not a good NFR as it is very difficult to verify. The stated method of verification is not a good way to verify this because it does not cover the majority of cases this requirement is covering. Also it is a bit ambiguous as there are multiple ways to "use" the app. We would recommend instead restricting the app to a specific language or be universal through the use of symbols.

TAs: @NickCapstone @tomashetMcMaster

**Comment by bassie184** [comment]
Removed this requirement and added an assumption that the user speaks English.
