### ISSUE TITLE
Team3 Review: Non-Functional Requirement for "Visual Appeal"

### ISSUE THREAD

**Issue by arkinmodi** [NevoAbigail/Capstone#12]
> NFR4: The design must be visual appealing.
> Rationale: Our lock must be visual appealing for it to be a desirable product.
> Verification: Design willbe verified with test users who will rank visual how appealing the lock is.

This NFR is not an easily verifiable requirement. The idea of using test users will always be subject to biases. We recommend either narrowing this down to a specific measurable component or removing it entirely.

TAs: @NickCapstone @tomashetMcMaster

**Comment by bassie184** [comment]
Considered this comment but have decided to keep the requirement.

**Comment by NevoAbigail** [comment]
This is definitely a subjective opinion, and will be assessed by asking users for their opinion on visual appeal on a 1-10 scale, as identified in the VnVPlan
