### ISSUE TITLE
Team3 Review: Conflicting Scope and Assumption

### ISSUE THREAD

**Issue by arkinmodi** [NevoAbigail/Capstone#14]
> 2.2 Scope of Requirements
> 7. Be waterproof.

> 4.1.3 Assumptions
> A3: The lock will be weatherproof.

In your scope, you state that it will be waterproof, but you also assume that the lock will be weatherproof. These statements conflict and sound like you are assuming it will do something that you should be designing for.

TAs: @NickCapstone @tomashetMcMaster

**Comment by bassie184** [comment]
Removed waterproof requirements, kept weatherproof assumption.
