### ISSUE TITLE
Team3 Review: Missing Stakeholders and Health/Safety/Cultural Factors

### ISSUE THREAD

**Issue by arkinmodi** [NevoAbigail/Capstone#16]
There are missing stakeholder (e.g., society, the development team) and Health/Safety/Cultural factors. An example of a safety measure is to prevent injuries during use to the user (e.g., do not clamp down on the user's finger, will not be moving at a speed or force that can cause injuries).

TAs: @NickCapstone @tomashetMcMaster

**Comment by bassie184** [comment]
Added a requirement for safety.
