### ISSUE TITLE
Team3 Review: Additional Feedback

### ISSUE THREAD

**Issue by arkinmodi** [NevoAbigail/Capstone#17]
- You state "Bluetooth wireless connective capabilities" is out of your scope, however your product/app will be using Bluetooth to connect to the lock. This is a bit confusing and sounds conflicting.
- Should GPS signal be an input in the System Context?
- The problem statement mentions how current locking systems may not lock the seat, however your product does not mention being able to do this either.

TAs: @NickCapstone @tomashetMcMaster

**Comment by bassie184** [comment]
Edited the Bluetooth inconsistency. GPS is not a signal in the System Context.
