### ISSUE TITLE
Team 5 Review - Hazard Analysis

### ISSUE THREAD

**Issue by yuvrajrr** [NevoAbigail/Capstone#20]
The Hazard Analysis looks great! One thing I would suggest is specifying the Safety and Security requirements beyond Functional and Non Functional Requirements. For example, including Access Requirements, Integrity Requirements, Privacy Requirements, etc. This way it'll be easier to plan for all aspects of the project as well as track progress throughout!

**Comment by bassie184** [comment]
Access, integrity and privacy requirements included in FR3, FR4 and NFR8. Comment deemed inadmissible due to project being Mechatronics-based.
