### ISSUE TITLE
Team 5 Review - Hazard Analysis

### ISSUE THREAD

**Issue by dimitritsampiras** [NevoAbigail/Capstone#21]
One of the critical assumptions is that the lock should operate in a location where GPS and Bluetooth are receivable. However, seeing as this is a hazard that could frequently occur, I think it would be beneficial to explore some functionality that would address it. Perhaps letting the operator know that GPS or Bluetooth are inaccessible so that they could find another location to lock their bike.

**Comment by bassie184** [comment]
A good suggestion but decided to be out of the scope of this project.
