### ISSUE TITLE
Team 5 Review - Hazard Analysis - Critical Assumptions

### ISSUE THREAD

**Issue by bentvelj** [NevoAbigail/Capstone#22]
I think some of the critical assumptions are a little bit too ambiguous. For example, 

> Assume operator's bicycle has standard frame and dimensions, and functions properly. 

What is a standard frame size for a bicycle? I think there should be numerical size constraints instead, which are unambiguous. Also,

> Assume weather is typical of Canada (i.e. no natural disasters).

What do you define as a natural disaster? What is typical weather of Canada? Again, I think something like 

> The device shall not be operated in temperatures outside the range of -30 degrees Celsius to +40 degrees Celsius.

would be more concrete.

Other than that, Hazard Analysis looks very thorough, well done!

**Comment by bassie184** [comment]
Added constraining numerical bike sizes and dimensions under critical assumptions as well as the temperature assumption.
