### ISSUE TITLE
Team 5 Review - Hazard Analysis - Matching new Requirements to FMEA table

### ISSUE THREAD

**Issue by Wililee** [NevoAbigail/Capstone#23]
When adding new requirements make sure that they can be used as solutions or _Recommended Actions_

For example one of the newly added safety requirements (which is a good one) is:

- The locking mechanism shall be able to disengage manually (e.g., with a key), in addition to remotely.

However in the FMEA table there is a section on what happens if the lock doesn't disengage. \
In the reasons stated there are many related to software-hardware malfunctions but none related to environmental causes such as 'dirt getting stuck in the lock'
All the solutions to this problem involve restarting the software rather than just using the key which would be the simplest solution in most cases if there is a key.

Here you can also match the use of the manual key as a recommended action.

As a side note: make sure if there is a plan for the use of a key there will need to be further security into creating key-locks that are not 'easily' unlocked and more requirements will need to follow for this component.

**Comment by bassie184** [comment]
A good comment but the feature of an additional manual key was decided to be out of the scope of this project.
