### ISSUE TITLE
Team 5 Review - Hazard Analysis - Requirements

### ISSUE THREAD

**Issue by MatthewWMcC** [NevoAbigail/Capstone#24]
The Hazard document looks very thourough although I would advise reviewing some frequently used terms. Namely, the term "normal" seems overused and can be probematic because normalcy can vary from person to person or between locations. When you state

>   NFR6: The lock must be waterproofed to withstand normal rainfall.

and 

> NFR7: The lock must be waterproofed to withstand normal splashing while riding.

these may be confusing to readers in other climates because the definition of normal rainfall may vary. Please consider being more specific with the levels of rainfall that you intend to support.

**Comment by bassie184** [comment]
Added rainfall and splashing specifications to Safety Requirements.
