### ISSUE TITLE
Team 5 Review - Hazard Analysis

### ISSUE THREAD

**Issue by BasselR** [NevoAbigail/Capstone#25]
Great job on your hazard analysis!
One insight I'd have would be regarding your first critical assumption, CA1:
> Assume operator is not tampering or purposefully damaging the product.

While assuming that operators will not purposefully misuse / damage the product is fair, it may be worthwhile to analyze the hazards and risks associated with accidental misuse by operators. 

What if the lock is engaged or disengaged when it is not meant to be - due to improper use? How can this affect the user - and what actions can be taken to mitigate the associated risks?

**Comment by bassie184** [comment]
This is covered in more recent documents and updated documents.
