### ISSUE TITLE
Team 1 Review: TeX File Does not Build, Document Missing Features.

### ISSUE THREAD

**Issue by Jonathan-Hai** [NevoAbigail/Capstone#28]
Team 1 pulled the Repo and attempted to build the VnVPlan.tex file, but it failed to build. It seems as if the PDF file was generated through different means instead of being generated by this TeX file. In addition, none of the links within the document are functional; both internally and externally.

Team 1 TA: @NickCapstone

**Comment by bassie184** [comment]
PDF was recompiled and pushed.
