### ISSUE TITLE
Team 1 Review: Verification and Validation Team Table Content Insufficient

### ISSUE THREAD

**Issue by Jonathan-Hai** [NevoAbigail/Capstone#29]
In section 4.1, the Verification and Validation Team Table only describes the general roles of the team members of Team 5 within the project itself. This table should describe how each specific portion of the verification and validation testing work is to be split between team members.

Team 1 TA: @NickCapstone

**Comment by bassie184** [comment]
This comment was not found to be valid for the development team.

**Comment by NevoAbigail** [comment]
Table revised with descriptions of testing responsibilities added.
