### ISSUE TITLE
Team 1 Review: Implementation Verification Plan Not Concrete

### ISSUE THREAD

**Issue by Jonathan-Hai** [NevoAbigail/Capstone#30]
In section 4.4, The Implementation Verification Plan only mentions the general ways in which functional and non-functional requirements are meant to be tested. This section should be linking specific tests to specific functional and non-functional requirements, and describe exactly how each requirement is fulfilled by said test.

Team 1 TA: @NickCapstone

**Comment by NevoAbigail** [comment]
This description has been added to the section.
