### ISSUE TITLE
Team 1 Review: SRS Verification Checklist Missing

### ISSUE THREAD

**Issue by Jonathan-Hai** [NevoAbigail/Capstone#31]
This document refers to an SRS Verification Checklist in Section 4.2. This checklist is missing in the VnV Plan, and cannot be found in the SRS document.

Team 1 TA: @NickCapstone

**Comment by bassie184** [comment]
Not required.

**Comment by NevoAbigail** [comment]
SRS Checklist in question is hyperlinked in the VnV plan, where it is mentioned.
