### ISSUE TITLE
Team 1 Review: System Tests Missing Information

### ISSUE THREAD

**Issue by Jonathan-Hai** [NevoAbigail/Capstone#32]
The System Tests in Section 5 are missing information. There should be a small introductory blurb at the beginning of each testing subsection describing how these tests fulfill the appropriate requirements. In addition, there are no descriptive Test IDs.

Team 1 TA: @NickCapstone

**Comment by NevoAbigail** [comment]
Each requirement maps directly to a test case, so we thought that writing a blurb for each test case would be unnecessary, however, it was added to the introduction of the Functional & Nonfunctional Requirement Test sections that this is the case--the tests are meant to directly fulfill whichever requirements they are mapped to. Descriptive Test IDs have been added to each test.
