### ISSUE TITLE
Team30 Review - [MIS] 9.4.4 - Access Routine Semantics of BTConnect()

### ISSUE THREAD

**Issue by edwin-do** [NevoAbigail/Capstone#43]
-	Transition needs to indicate a change in a state or environment variable
-	Could include an environment variable to indicate the Bluetooth connection status such as StatusBT of type boolean
-	Can modify the value of StatusBT as the transition 

P.S. Can not add label to issue

**Comment by NevoAbigail** [comment]
Bluetooth Connection Module replaced with Mobile App Bluetooth Communication and Arduino Bluetooth Communication, Mobile App Bluetooth Communication has state variable isConnected
