### ISSUE TITLE
Team30 Review - [MIS] 10.4.4 - Access Routine Semantics of getBatteryStatus()

### ISSUE THREAD

**Issue by edwin-do** [NevoAbigail/Capstone#44]
-	Missing output, should return a value or a data object containing the battery status 
-	BatteryStatus can be a state variable that can be stored in memory
-	Can also include couple simple exceptions where the value is NULL or a negative value

P.S. Can not add label to issue

**Comment by NevoAbigail** [comment]
Revised Battery Status module to include output, batteryPercentage variable
