### ISSUE TITLE
Team30 Review - [MIS] 11.4.4 - Formalize a critical portion of the document

### ISSUE THREAD

**Issue by edwin-do** [NevoAbigail/Capstone#45]
-	Access Routine Semantics of loadPower() is probably one of the more critical portion of this document so the output condition can be formalized with discrete math 
- Assigning the Arduino Pin’s value to a variable can help formalize and make the design more clear
-	Since this routine is more critical to the system, it should probably include some exceptions as well

P.S. Can not add label to issue

**Comment by NevoAbigail** [comment]
Assigned Arduino PIN value to a constant TRANSISTOR_OUT in module that replaced LoadPower (Hardware Disengage), also formalized the behaviour of this module (Hardware Disengage module) with discrete math
