### ISSUE TITLE
Team30 Review - [MIS] - 6. Input Parameter Module

### ISSUE THREAD

**Issue by edwin-do** [NevoAbigail/Capstone#48]
- The purpose of the module is unclear based on the specification, there is no exported constants, exported access programs or local functions
- Other modules would likely need to use this module, so there should be some form of exported constants or access programs
- Within other modules, it would also need to state this module as an import if it uses it afterwards
- Be sure that the communication between the modules in the specification is clear

**Comment by NevoAbigail** [comment]
This module has been deleted.
