### ISSUE TITLE
Team29 Review: Input/Output Details for Unit Tests

### ISSUE THREAD

**Issue by Kabishan** [NevoAbigail/Capstone#49]
Excellent work on the V & V Report. Good use of diagrams to consolidate test results.

Unit tests would benefit from the specification of inputs and outputs. For example, when connecting from the mobile app to the Arduino, it would have been useful to describe the actions you had taken on the mobile app to establish the connection (the function evoked when pressing a button on the app or when opening the app), and correspondingly, how you were able to validate the connection on the Arduino.

@CSchank

**Comment by NevoAbigail** [comment]
Added setup, input, expected result/output for Unit Test to Vnv Plan. Summary of results is then listed in a table in the VnV Report, and the VnV plan is referenced to get the full details of the test
