### ISSUE TITLE
Team29 Review:  Test  description for functional requirements

### ISSUE THREAD

**Issue by GaryGong27** [NevoAbigail/Capstone#50]
Very good report with diagrams and graphs that helps visualize the test result!

For the FR testing and NFR testing section,  adding users/tester action in each of the test case would be helpful ias it will help readers understand the context and steps performed for each test.

@CSchank

**Comment by NevoAbigail** [comment]
This is described in the VnV Plan--added this note and referenced the VnV Plan at the beginning of the FR and NFR Evaluation sections
