### ISSUE TITLE
Team 29 Review: Expected Results

### ISSUE THREAD

**Issue by JAYapeter** [NevoAbigail/Capstone#52]
Great work on the VnV report! 

One thing I think can be improved a bit more detail in the tests. As my teammate Gary mentioned, explaining the process or action taken for each test would help give context to how each test was actually performed. Another detail I think some tests are missing is being more specific in the Expected Results. For example, for the test VisualAppeal, the expected result is that a majority of surveyed users should deem the visual appeal satisfactory. Having a scale in the description would help the readers more easily understand the test, rather than leave it to the graph in Figure 7.

@CSchank

**Comment by NevoAbigail** [comment]
Added detail to expected results--namely, added the rating which is deemed satisfactory in the Visual Appeal test
