### ISSUE TITLE
Team29 Review: User feedback details

### ISSUE THREAD

**Issue by davidwyao** [NevoAbigail/Capstone#53]
Neat project idea, quite thoroughly tested.

I'd be interested in seeing more details about how your users responded to your survey questions. The document provides a broad summary about what most people said, but it may be helpful to include more specific details in a different document, or in additional figures like your visual appeal ranking graph. This could also make it easier to see all the results from your requirement test subjects in one place.

@CSchank

**Comment by NevoAbigail** [comment]
Added these results in UserTesting.xlsx in VnVReport folder and referenced this document within the VnVReport
